---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
generator:
  name: "NewQuerySideProject"
  group: "my-company-rugs"
  artifact: "query-side-project-generator"
  version: "0.1.1"
  origin:
    repo: "git@github.com:ivans-innovation-lab/my-company-rugs-materialized-view-generator.git"
    branch: "master"
    sha: "c9ded8b"
  parameters:
    - "aggregateName": "Customer"
    - "version": "0.1.0-SNAPSHOT"
    - "description": "my new project"

